- app/Http/Controllers/Admin/AdminController.php
- app/Http/Controllers/Admin/CategoryController.php
- app/Http/Controllers/Admin/ProductController.php
- app/Http/Controllers/Admin/UserController.php
- app/Http/Controllers/ImageController.php
- composer.lock
- package-lock.json
- package.json
- resources/css/admin.css
- resources/js/Components/Admin/BreadcrumbHistory/BreadcrumbHistory.jsx
- resources/js/Components/Admin/Dashboard/BrowserStats.jsx
- resources/js/Components/Admin/Dashboard/ProductOrders.jsx
- resources/js/Components/Admin/Dashboard/RecentOrders.jsx
- resources/js/Components/Admin/Dashboard/RevenueChart.jsx
- resources/js/Components/Admin/Dashboard/StatCard.jsx
- resources/js/Components/Admin/DataTable.jsx
- resources/js/Components/Admin/Header/AdminHeader.jsx
- resources/js/Components/Admin/PageHeader.jsx
- resources/js/Components/Admin/Sidebar/AdminSidebar.jsx
- resources/js/Components/Admin/Sidebar/LinksGroup.jsx
- resources/js/Layouts/AdminLayout.jsx
- resources/js/Pages/Admin/Categories/Index.jsx
- resources/js/Pages/Admin/Dashboard.jsx
- resources/js/Pages/Admin/Products/Index.jsx
- resources/js/Pages/Admin/Users/Index.jsx
- routes/admin.php
- routes/web.php
- Thêm components, layouts, pages cho admin quản lý (products, categories, users)
- Thêm controller Admin để điều hướng đến các trang dashboard và index
- Mới kiểm tra xác thực người dùng đăng nhập ở Frontend
- Chưa có xác thực admin
[Redmine Ticket](https://edu-redmine.sun-asterisk.vn/issues/90608)
> Feature FE#90608 Thêm Admin Layout

- resources/js/Pages/Auth/ForgotPassword.jsx
- resources/js/Pages/Auth/ResetPassword.jsx
- resources/js/Pages/Auth/VerifyEmail.jsx
tạo giao diện cho trang quên mật khẩu
> [Feature #90361] quên mật khẩu

- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Requests/Auth/LoginRequest.php
- app/Models/User.php
Thực hiện tác vụ đăng ký, đăng nhập sử dụng laravel authentication.
> [Feature #90311] đăng ký, đăng nhập

- routes/web.php
Thực hiện các thay đổi sau trong .env: 
MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME="your_gmail_address@gmail.com" // địa chỉ mail gửi mail cho các tài khoản mail quên mật khẩu
MAIL_PASSWORD="your_16_character_app_password"//16 ký tự mật khẩu ứng dụng sau khi bật xác thực 2 bước google.
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS="your_gmail_address@gmail.com"//địa chỉ mail gửi mail cho các tài khoản mail quên mật khẩu
MAIL_FROM_NAME="${APP_NAME}"
> [Feature #90317] quên mật khẩu

- app/Http/Controllers/ProductController.php
- app/Http/Controllers/User/HomeController.php
- resources/css/app.css
- resources/js/Components/User/Features.jsx
- resources/js/Components/User/Footer.jsx
- resources/js/Components/User/Header.jsx
- resources/js/Components/User/Hero.jsx
- resources/js/Components/User/NewArrivals.jsx
- resources/js/Components/User/ProductFilters.jsx
- resources/js/Components/User/ProductGrid.jsx
- resources/js/Components/User/ProductSorting.jsx
- resources/js/Components/User/TopSellingProducts.jsx
- resources/js/Layouts/UserLayout.jsx
- resources/js/Pages/User/Home.jsx
- resources/js/Pages/User/Product_details.jsx
- resources/js/Pages/User/Product_index.jsx
- routes/web.php
[redmine ticket](https://edu-redmine.sun-asterisk.vn/issues/90325)
> [Feature #90325] Khách hàng xem danh sách sản phẩm

- app/Http/Controllers/Admin/ProductController.php
- app/Http/Controllers/ImageController.php
- app/Http/Requests/Admin/StoreProductRequest.php
- app/Http/Requests/Admin/UpdateProductRequest.php
- resources/js/Pages/Admin/Products/Edit.jsx
- resources/js/Pages/Admin/Products/Show.jsx
- routes/admin.php
- routes/web.php
- Hoàn thiện backend cho crud products
- Thêm 2 file request validate cho store và update products
- Thêm middleware is_admin cho các route admin
- Sửa lại route và controller products cho đúng quy phạm
- **_Lưu ý:_** Cần chạy `php artisan storage:link` để tạo symbolic link từ storage đến public để truy cập file ảnh qua url
[Redmine Ticket](https://edu-redmine.sun-asterisk.vn/issues/90324)
> [Feature BE#90324] Backend cho CRUD admin products

- app/Http/Controllers/Admin/CategoryController.php
- app/Http/Controllers/Auth/GoogleController.php
- composer.lock
- package-lock.json
- package.json
- resources/js/Components/TextareaInput.jsx
- resources/js/Layouts/AdminLayout.jsx
- resources/js/Pages/Admin/Categories/Create.jsx
- resources/js/Pages/Admin/Categories/Edit.jsx
- resources/js/Pages/Admin/Categories/Index.jsx
- resources/js/Pages/Admin/Categories/Show.jsx
- routes/admin.php
- Edit danh mục sản phẩm:  
- Delete danh mục sản phẩm:
- Bổ sung thêm chức năng xem chi tiết danh mục sản phẩm:
> [Feature #90322] [BE]CRUD danh mục (Update, delete)

- app/Http/Controllers/Admin/ProductController.php
- app/Http/Controllers/Auth/GoogleController.php
- app/Http/Controllers/ImageController.php
- composer.lock
- database/seeders/ProductImagesSeeder.php
- resources/js/Components/Admin/DataTable.jsx
- resources/js/Components/Admin/Pagination.jsx
- resources/js/Components/Admin/PerPageSelector.jsx
- resources/js/Pages/Admin/Products/Index.jsx
- Thêm 2 components xử lý phân trang và chọn trang
- Đưa tất cả filter, sort, search xử lý server-side xử lý ở backend
- Xóa những code không cần thiết ở DataTable Components
[Redmine Ticket](https://edu-redmine.sun-asterisk.vn/issues/91139)
> [Feature #91139] Thêm Pagination cho Admin Products Index

- app/Models/Feedback.php
- app/Models/OrderDetail.php
- app/Models/Product.php
- app/Models/User.php
- database/migrations/2025_08_15_105105_add_order_detail_id_to_feedbacks_table.php
- Xóa trường user_id và product_id
- Thêm trường order_details_id
- Sửa các model theo thay đổi tương ứng 
- _**Lưu ý:**_ Cần chạy `php artisan migrate` để update database
[Redmine ticket](https://edu-redmine.sun-asterisk.vn/issues/91290)
> [Task Model#91290] Update migrations & models Feedbacks

- app/Http/Controllers/OrderController.php
- database/factories/OrderDetailFactory.php
- database/factories/OrderFactory.php
- database/seeders/DatabaseSeeder.php
- database/seeders/OrderSeeder.php
- resources/js/Pages/User/OrderDetail.jsx
- resources/js/Pages/User/OrderHistory.jsx
[https://edu-redmine.sun-asterisk.vn/issues/91323](url)
- Hiển thị danh sách đơn hàng theo thứ tự gần ngày hiện tại nhất hoặc xa ngày hiện tại nhất: 
- Xem chi tiết đơn hàng :
> [Feature #91323] [BE] User xem đơn hàng, danh sách đơn hàng

- app/Http/Controllers/Auth/AuthenticatedSessionController.php
- app/Http/Controllers/FeedbackController.php
- app/Http/Controllers/ImageController.php
- app/Http/Requests/DeleteFeedbackImageRequest.php
- app/Http/Requests/StoreFeedbackRequest.php
- app/Http/Requests/UpdateFeedbackRequest.php
- app/Models/Feedback.php
- resources/js/Components/Admin/Sidebar/AdminSidebar.jsx
- resources/js/Components/User/FeedbackImageUpload.jsx
- resources/js/Components/User/Header.jsx
- resources/js/Pages/Admin/Products/Index.jsx
- resources/js/Pages/User/Feedbacks.jsx
- resources/js/locales/en.json
- routes/admin.php
- routes/web.php
- Thêm nút My Feedbacks ở Header của User để redirect đến /feedbacks
- Thêm các trang User đánh giá order đã completed
- Trang sản phẩm chưa đánh giá (những orderdetails đã completed chưa có feedbacks)
- Trang sản phẩm đã đánh giá (những orderdetails đã completed đã có feedbacks)
- Modal tạo feedback mới (thêm ảnh vào feedbacks tối đa 5 ảnh)
- Modal chỉnh sửa feedbacks
- Chỉnh sửa route admin khi đăng nhập thành công sẽ redirect đến /admin/dashboard
[Redmine Ticket FE](https://edu-redmine.sun-asterisk.vn/issues/91294)
[Redmine Ticket BE](https://edu-redmine.sun-asterisk.vn/issues/91295)
- Nút My Feedbacks
- Trang sản phẩm chưa đánh giá
- Trang sản phẩm đã đánh giá
- Modal tạo đánh giá mới 
- Modal chỉnh sửa đánh giá
> [Feature FE#91294] [Feature BE#91295] User đánh giá sản phẩm đã nhận hàng thành công

- app/Http/Controllers/Admin/OrderController.php
- app/Http/Controllers/Admin/OrderDetailController.php
- app/Http/Controllers/Admin/ProductController.php
- app/Models/Product.php
- resources/js/Pages/Admin/Orders/Edit.jsx
- resources/js/Pages/Admin/Products/Index.jsx
- Sửa logic admin chỉnh sửa status order pending -> processing -> completed -> canceled 
- Thêm ràng buộc và thông báo khi xóa Products 
[Redmine Ticket](https://edu-redmine.sun-asterisk.vn/issues/91765)
- pending -> processing -> completed -> canceled 
- Thêm ràng buộc khi xóa Products
> [Task #91765] Sửa logic admin update status order 

- app/Http/Controllers/Admin/OrderController.php
- app/Http/Controllers/BillingController.php
- app/Http/Controllers/OrderController.php
- app/Http/Requests/CheckoutRequest.php
- app/Models/Order.php
- app/Models/OrderDetail.php
- app/Services/CartService.php
- database/migrations/2025_08_21_164018_cart_item_change.php
- database/migrations/2025_08_21_172512_adjust_order_table.php
- database/migrations/2025_08_21_195817_separated_order_detail.php
- database/seeders/DatabaseSeeder.php
- resources/js/Pages/Admin/Orders/Edit.jsx
- resources/js/Pages/User/Checkout.jsx
- resources/js/Pages/User/OrderDetail.jsx
- resources/js/Pages/User/Product_details.jsx
- resources/js/Pages/User/ShoppingCart.jsx
- resources/js/locales/en.json
- resources/js/locales/vi.json
[redmine ticket](https://edu-redmine.sun-asterisk.vn/issues/91960)
-Khi xóa sản phẩm sẽ không xóa trong giỏ hàng mà có thông báo rằng sản phẩm đã bị xóa.
-Khi chỉnh sửa sản phẩm sẽ có thông báo trong giỏ hàng của người dùng có sản phẩm đó.
-Thêm dữ liệu cứng trong order_details để đảm bảo thông tin về tên và giá của sản phẩm trong đơn hàng không bị thay đổi khi sản phẩm bị xóa hay thay đổi.
-Thêm thông tin số lượng sản phẩm trong kho và giới hạn mức tối đa có thể thêm vào giỏ hàng.
-Đổ dữ liệu địa chỉ người dùng từ đơn hàng gần nhất.
> [Task #91960] Sửa một số lỗi còn tồn tại trong sprint 2

- .gitignore
- app/Http/Controllers/Admin/ProductController.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Interfaces/ProductRepositoryInterface.php
- app/Repositories/ProductRepository.php
- app/Services/ProductService.php
- database/factories/OrderDetailFactory.php
- database/factories/OrderFactory.php
- database/seeders/DatabaseSeeder.php
- database/seeders/OrderSeeder.php
- phpunit.xml
- tests/Unit/Http/Controllers/Admin/ProductControllerTest.php
- tests/Unit/Models/ProductTest.php
- tests/Unit/README.md
- tests/Unit/Repositories/ProductRepositoryTest.php
- tests/Unit/Services/ProductServiceTest.php
- Sửa lại Seeder cho đúng với database sau chỉnh sửa
- Refactor code CRUD products với services, repositories layer
- Test với models, services, repositories, controllers của products
- Hướng dẫn test tại file `tests/Unit/README.md`
[Redmine Ticket](https://edu-redmine.sun-asterisk.vn/issues/92102)
> [Task #92102] UnitTest cho CRUD Products

- app/Http/Controllers/BillingController.php
- app/Http/Controllers/OrderController.php
- app/Models/Order.php
- app/Services/ShippingService.php
- database/migrations/2025_08_22_164908_add_tax_and_shipping_fee.php
- resources/js/Pages/User/Checkout.jsx
- resources/js/Pages/User/OrderDetail.jsx
- routes/api.php
[redmine ticket](https://edu-redmine.sun-asterisk.vn/issues/92112)
-Tạo service ShippingService để tính phí vận chuyển hàng hoá.
-Sử dụng api để tính toán phí vận chuyển từ front end.
> [Feature #92112] Tạo service cho tính phí vận chuyển

- app/Http/Controllers/Admin/AdminController.php
- app/Http/Kernel.php
- app/Http/Middleware/HandleInertiaAdminRequests.php
- app/Models/User.php
- database/factories/OrderDetailFactory.php
- database/seeders/OrderSeeder.php
- resources/js/Components/Admin/Dashboard/ProductOrders.jsx
- resources/js/Components/Admin/Dashboard/RecentOrders.jsx
- resources/js/Components/Admin/Dashboard/RevenueChart.jsx
- resources/js/Components/Admin/Header/AdminHeader.jsx
- resources/js/Components/Admin/Sidebar/AdminSidebar.jsx
- resources/js/Pages/Admin/Dashboard.jsx
- routes/admin.php
- routes/web.php
[https://edu-redmine.sun-asterisk.vn/issues/91325?issue_count=5&issue_position=4&next_issue_id=91324&prev_issue_id=91960](url)
dashboard BE
> [User stories #91325] [BE] Dashboard

- app/Console/Commands/DailyRevenueReport.php
- app/Console/Kernel.php
- app/Console/README.md
- app/Mail/DailyRevenueReportMail.php
- database/seeders/TestOrderSeeder.php
- resources/views/emails/daily-revenue-report.blade.php
- Thêm seeder testorders để thêm các orders ngày hôm trước
- Tạo command gửi báo cáo doanh thu hàng ngày cho admin
- Tạo schedule mỗi 7h sáng gửi báo cáo ngày hôm trước
- Tạo mailer để gửi qua mail 
- Tạo views để gửi bằng template blade
_**Lưu ý:**_ Hướng dẫn config email stmp, run/test command, schedule, cronjob ở file `app/Console/README.md`
[Redmine Ticket](https://edu-redmine.sun-asterisk.vn/issues/92157)
> [Feature CronJob#92157] Tạo schedule, command gửi mail(Mailer) báo cáo doanh thu hằng ngày cho admin

- app/Http/Controllers/Admin/CategoryController.php
- app/Providers/AppServiceProvider.php
- app/Repositories/CategoryRepository.php
- app/Repositories/Interfaces/CategoryRepositoryInterface.php
[https://edu-redmine.sun-asterisk.vn/issues/92162](url)
> [Feature #92162] Tách code CRUD danh mục thành Repository layer.

- app/Events/OrderPlaced.php
- app/Http/Controllers/Admin/NotificationController.php
- app/Http/Controllers/BillingController.php
- app/Http/Kernel.php
- app/Http/Middleware/HandleInertiaAdminRequests.php
- app/Listeners/SendNewOrderNotification.php
- app/Notifications/NewOrderNotification.php
- app/Providers/EventServiceProvider.php
- database/migrations/2025_08_27_160106_create_notifications_table.php
- resources/js/Components/Admin/Header/AdminHeader.jsx
- resources/js/Pages/Admin/Notifications/Index.jsx
- routes/admin.php
[https://edu-redmine.sun-asterisk.vn/issues/92161](url)
- Thông báo qua mail: 
- Thông báo trên web:
> [Feature #92161] Thông báo cho admin khi có đơn hàng mới

- app/Http/Controllers/Api/UserApiController.php
- composer.json
- composer.lock
- public/swagger/openapi.json
- routes/api.php
[redmine ticket](https://edu-redmine.sun-asterisk.vn/issues/92508)
Thêm documentation cho admin quản lý user.
> [Feature #92508] api documentation cho admin quản lý người dùng.
